[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
arcpay = "GVbnwYVXEVtrNKALkNhzyiQvLErtUnpjQG8J18r3i7iz"

[programs.devnet]
arcpay = "GVbnwYVXEVtrNKALkNhzyiQvLErtUnpjQG8J18r3i7iz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
